import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import "./styles.css";

const API = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000/api";
const labels = { ACORDO: "Acordo", DEFESA: "Defesa", BANCO: "Banco", ADVOGADO_EXTERNO: "Advogado externo", ADMIN_GLOBAL: "Admin global" };
const money = (value) => value == null ? "—" : new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);

async function request(path, options = {}) {
  const response = await fetch(API + path, { credentials: "include", ...options });
  if (response.status === 204) return null;
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.detail || `Erro ${response.status}`);
  return data;
}

function Login({ onLogin }) {
  const [error, setError] = useState("");
  const [pending, setPending] = useState(false);
  const submit = async (event) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true); setError("");
    try { onLogin(await request("/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) })); }
    catch (cause) { setError(cause.message); } finally { setPending(false); }
  };
  return <main className="login-page"><section className="login-card"><p className="eyebrow">ENTEROS · BANCO UNICAMP</p><h1>EnterAgree</h1><p>Acesse sua área de operação.</p><form onSubmit={submit}><label>E-mail<input name="email" type="email" required autoComplete="email" /></label><label>Senha<input name="password" type="password" required autoComplete="current-password" /></label>{error && <p className="warning" role="alert">{error}</p>}<button disabled={pending}>{pending ? "Entrando…" : "Entrar"}</button></form></section></main>;
}

function Shell({ user, onLogout, children }) {
  const base = user.role === "BANCO" ? "/banco" : user.role === "ADVOGADO_EXTERNO" ? "/advogado" : "/admin";
  return <main className="shell"><header><div><p className="eyebrow">ENTEROS · {user.bank_name || "PLATAFORMA"}</p><h1>EnterAgree</h1><p>{labels[user.role]} · {user.name}</p></div><nav><Link to={base}>Início</Link>{user.role === "BANCO" && <Link to="/banco/monitoramento">Monitoramento</Link>}<button className="secondary" onClick={onLogout}>Sair</button></nav></header>{children}</main>;
}

function Cases({ user }) {
  const [cases, setCases] = useState([]); const [lawyers, setLawyers] = useState([]); const [error, setError] = useState(""); const navigate = useNavigate();
  const load = async () => { try { setCases(await request("/cases")); if (user.role === "BANCO") setLawyers(await request("/bank/lawyers")); } catch (cause) { setError(cause.message); } };
  useEffect(() => { load(); }, []);
  const create = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const item = await request("/cases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ case_number: form.get("case_number"), uf: form.get("uf"), value_of_claim: Number(form.get("value_of_claim")), sub_subject: form.get("sub_subject") || null, assigned_lawyer_id: form.get("assigned_lawyer_id") || null }) }); event.currentTarget.reset(); navigate(`/banco/casos/${item.id}`); } catch (cause) { setError(cause.message); } };
  return <section className="role-layout">{error && <p className="warning">{error}</p>}<article className="panel"><h2>{user.role === "BANCO" ? "Abrir novo processo" : "Meus processos"}</h2>{user.role === "BANCO" && <form onSubmit={create}><label>Número do processo<input name="case_number" required minLength="3" /></label><div className="row"><label>UF<input name="uf" defaultValue="SP" required maxLength="2" /></label><label>Valor da causa<input name="value_of_claim" type="number" min="0" required /></label></div><label>Subassunto<input name="sub_subject" defaultValue="Não reconhecimento de empréstimo" /></label><button>Abrir processo</button></form>}</article><article className="panel"><h2>{user.role === "BANCO" ? "Processos do banco" : "Processos sob sua responsabilidade"}</h2>{cases.length ? <div className="cases">{cases.map((item) => <Link className="case-card link-card" key={item.id} to={user.role === "BANCO" ? `/banco/casos/${item.id}` : `/advogado/casos/${item.id}`}><strong>{item.case_number}</strong><span>{item.uf} · {money(item.value_of_claim)}{item.assigned_lawyer_id ? " · Responsável atribuído" : " · Sem responsável"}</span></Link>)}</div> : <p className="muted">Nenhum processo disponível.</p>}</article></section>;
}

function CaseDetail({ user }) {
  const { caseId } = useParams(); const [detail, setDetail] = useState(null); const [lawyers, setLawyers] = useState([]); const [error, setError] = useState("");
  const load = async () => { try { setDetail(await request(`/cases/${caseId}`)); if (user.role === "BANCO") setLawyers(await request("/bank/lawyers")); } catch (cause) { setError(cause.message); } };
  useEffect(() => { load(); }, [caseId]);
  const assign = async (event) => { const lawyer = event.target.value || null; try { await request(`/cases/${caseId}/assignment`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assigned_lawyer_id: lawyer }) }); load(); } catch (cause) { setError(cause.message); } };
  const analyze = async () => { try { await request(`/cases/${caseId}/analyses`, { method: "POST" }); load(); } catch (cause) { setError(cause.message); } };
  const decide = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request(`/cases/${caseId}/lawyer-decisions?analysis_id=${detail.analyses[0].id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: form.get("action"), proposed_value: form.get("value") ? Number(form.get("value")) : null, reason: form.get("reason") || null }) }); event.currentTarget.reset(); load(); } catch (cause) { setError(cause.message); } };
  if (error) return <p className="warning">{error}</p>; if (!detail) return <p>Carregando processo…</p>;
  const recommendation = detail.analyses?.[0]; const decision = detail.lawyer_decisions?.[0];
  return <section className="workspace"><Link to={user.role === "BANCO" ? "/banco" : "/advogado"}>← Voltar aos processos</Link><div className="case-title"><div><p className="eyebrow">PROCESSO</p><h2>{detail.case.case_number}</h2><p>{detail.case.uf} · {money(detail.case.value_of_claim)}</p></div>{user.role === "ADVOGADO_EXTERNO" && <button className="primary" onClick={analyze}>Avaliar risco e recomendação</button>}</div>{user.role === "BANCO" && <article className="panel"><h3>Advogado responsável</h3><select value={detail.case.assigned_lawyer_id || ""} onChange={assign}><option value="">Sem responsável</option>{lawyers.map((lawyer) => <option key={lawyer.id} value={lawyer.id}>{lawyer.name} · {lawyer.email}</option>)}</select></article>}<div className="cards"><article className="panel"><h3>Documentos do processo</h3>{detail.documents.length ? <ul>{detail.documents.map((document) => <li key={document.id}>{document.original_filename} · {document.declared_type} · {document.status}</li>)}</ul> : <p className="muted">Nenhum documento enviado.</p>}</article><article className="panel analysis"><h3>Saída da ferramenta</h3>{recommendation ? <><div className={`recommendation ${recommendation.recommendation === "ACORDO" ? "agreement" : "defense"}`}><span>Recomendação</span><strong>{labels[recommendation.recommendation]}</strong></div><p><b>Ação indicada:</b> {recommendation.recommendation === "ACORDO" ? "Propor acordo" : "Disputar a causa"}</p>{recommendation.pricing?.target_value != null && <p><b>Valor sugerido:</b> {money(recommendation.pricing.target_value)}</p>}<ul>{recommendation.reasons.map((reason, index) => <li key={index}>{reason}</li>)}</ul></> : <p className="muted">Aguardando avaliação do advogado.</p>}</article></div>{user.role === "ADVOGADO_EXTERNO" && recommendation && <article className="panel decision"><h3>Registrar decisão</h3><form onSubmit={decide}><label>Ação<select name="action" defaultValue={recommendation.recommendation}><option value="ACORDO">Acordo</option><option value="DEFESA">Defesa</option></select></label><label>Valor proposto<input name="value" type="number" min="0" /></label><label>Justificativa<textarea name="reason" /></label><button>Registrar decisão</button></form></article>}{decision && <p className="registered">Decisão registrada pelo advogado: {labels[decision.action] || decision.action}</p>}</section>;
}

function Monitoring() { const [data, setData] = useState(null); useEffect(() => { request("/monitoring").then(setData); }, []); return <article className="panel"><h2>Monitoramento do Banco</h2>{!data ? <p>Carregando…</p> : <div className="monitor"><Metric label="Análises" value={data.total_analyses}/><Metric label="Decisões" value={data.total_lawyer_decisions}/><Metric label="Aderência" value={data.adherence_rate == null ? "—" : `${(data.adherence_rate * 100).toFixed(1)}%`}/></div>}</article>; }
function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }

function Admin() { const [banks, setBanks] = useState([]); const [users, setUsers] = useState([]); const [error, setError] = useState(""); const load = () => Promise.all([request("/admin/banks"), request("/admin/users")]).then(([nextBanks, nextUsers]) => { setBanks(nextBanks); setUsers(nextUsers); }).catch((cause) => setError(cause.message)); useEffect(() => { load(); }, []); const addBank = async (event) => { event.preventDefault(); try { await request("/admin/banks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: new FormData(event.currentTarget).get("name") }) }); event.currentTarget.reset(); load(); } catch (cause) { setError(cause.message); } }; const addUser = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request("/admin/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); event.currentTarget.reset(); load(); } catch (cause) { setError(cause.message); } }; return <section className="role-layout">{error && <p className="warning">{error}</p>}<article className="panel"><h2>Bancos</h2><form onSubmit={addBank}><label>Nome<input name="name" required /></label><button>Cadastrar banco</button></form><ul>{banks.map((bank) => <li key={bank.id}>{bank.name}</li>)}</ul></article><article className="panel"><h2>Cadastro de advogados e usuários</h2><form onSubmit={addUser}><label>Nome<input name="name" required /></label><label>E-mail<input name="email" type="email" required /></label><label>Senha inicial (15+ caracteres)<input name="password" type="password" minLength="15" required /></label><label>Perfil<select name="role" defaultValue="ADVOGADO_EXTERNO"><option value="ADVOGADO_EXTERNO">Advogado externo</option><option value="BANCO">Banco</option><option value="ADMIN_GLOBAL">Admin global</option></select></label><label>Banco<select name="bank_id" defaultValue="banco-unicamp"><option value="">Nenhum (somente admin)</option>{banks.map((bank) => <option key={bank.id} value={bank.id}>{bank.name}</option>)}</select></label><button>Cadastrar usuário</button></form><ul>{users.map((user) => <li key={user.id}>{user.name} · {labels[user.role]} · {user.is_active ? "ativo" : "inativo"}</li>)}</ul></article></section>; }

export default function App() { const [user, setUser] = useState(undefined); const navigate = useNavigate(); useEffect(() => { request("/auth/me").then(setUser).catch(() => setUser(null)); }, []); const logout = async () => { await request("/auth/logout", { method: "POST" }); setUser(null); navigate("/login"); }; if (user === undefined) return <main className="login-page">Verificando sessão…</main>; if (!user) return <Routes><Route path="*" element={<Login onLogin={setUser} />} /></Routes>; const base = user.role === "BANCO" ? "/banco" : user.role === "ADVOGADO_EXTERNO" ? "/advogado" : "/admin"; return <Shell user={user} onLogout={logout}><Routes><Route path="/" element={<Navigate to={base} replace />}/><Route path="/login" element={<Navigate to={base} replace />}/><Route path="/banco" element={user.role === "BANCO" ? <Cases user={user}/> : <Navigate to={base} replace />}/><Route path="/banco/casos/:caseId" element={user.role === "BANCO" ? <CaseDetail user={user}/> : <Navigate to={base} replace />}/><Route path="/banco/monitoramento" element={user.role === "BANCO" ? <Monitoring/> : <Navigate to={base} replace />}/><Route path="/advogado" element={user.role === "ADVOGADO_EXTERNO" ? <Cases user={user}/> : <Navigate to={base} replace />}/><Route path="/advogado/casos/:caseId" element={user.role === "ADVOGADO_EXTERNO" ? <CaseDetail user={user}/> : <Navigate to={base} replace />}/><Route path="/admin" element={user.role === "ADMIN_GLOBAL" ? <Admin/> : <Navigate to={base} replace />}/></Routes></Shell>; }

createRoot(document.getElementById("root")).render(<BrowserRouter><App /></BrowserRouter>);
